DROP TABLE IF EXISTS favorite_maps CASCADE;

CREATE TABLE favorite_maps (
  id SERIAL PRIMARY KEY NOT NULL,
  created_at TIMESTAMP,
  removed_at TIMESTAMP DEFAULT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
